### ISSUE TITLE
[1.0.7]Mekanism and more Mods Items got invisible and visual broken in creative inventory.

### ISSUE THREAD

**Issue by yuusyaasisutanto** [MoePus/Flerovium#4]
I've confirmed my 620+ modded 1.20.1, but seems caused this in minimam configuration Mekanism and Flerovium .
it may cause in survival.
but I'm not mod dev, so sry for racking of detail.
I made incompatible list in 620+ modded 1.20.1 below as reference.

- Mekanism
- Create (0.5.1f) nixie tube got affected
- Obscure Tooltips (through [Obscure Tooltips Fix](https://www.curseforge.com/minecraft/mc-mods/obscure-tooltips-fix))
- EnderIO
- ImmersiveEngineering
- [Gauges and Switches Ported](https://www.curseforge.com/minecraft/mc-mods/gauges-and-switches-ported)
- Yuushya Townscape

![image](https://github.com/user-attachments/assets/a599891b-a7dd-420c-88b6-2f69baea4bb0)
![image](https://github.com/user-attachments/assets/910cd211-b504-44c5-812f-c229ca6b58aa)
![image](https://github.com/user-attachments/assets/a5cd4110-747a-41c8-9bfc-22cefabf5a70)
![image](https://github.com/user-attachments/assets/bc5a3255-17e0-47ab-b5e7-31e8d5739810)
![image](https://github.com/user-attachments/assets/bc8d828a-f4bf-469d-8493-457820aef129)
![image](https://github.com/user-attachments/assets/d7042ba1-7801-4cd4-b7fd-9084391c1126)
![image](https://github.com/user-attachments/assets/f3209c90-bf55-4c1d-95fd-f56b5a00af5a)

interesting, some items in Obscure Tooltips, some not affected this bugs(maybe it made by brockbench or something?)
![image](https://github.com/user-attachments/assets/e4085ea3-3dcb-4d94-a26f-eeb428b92a8a)

**Comment by MoePus** [comment]
Probably fixed in 1.1.0, feel free to reopen this issue if not fixed

**Comment by yuusyaasisutanto** [comment]
Thanks for fixing!
fixed all nearly, but Obscure Tooltips hadn't work correctly yet...

Obscure Tooltips seems closed source, so I don't force to say do fixing because it's difficult to fix this i thought.
but if you interest to fix this, perhaps "Obuscuria Collection" discord server might help you. 
you can reach from "issue" or "wiki" link in Obscure Tooltips's curse forge page.
https://www.curseforge.com/minecraft/mc-mods/obscure-tooltips

![image](https://github.com/user-attachments/assets/ea8acad2-a96b-435c-b843-02a6eac3405f)
correctly rendering when equiped :
![image](https://github.com/user-attachments/assets/06fe1487-a5c3-4175-81c1-1a749e2516af)


enabled Flerovium, it's like 2D and doesn't render backside:
![image](https://github.com/user-attachments/assets/640e5581-49f1-48dd-9cc8-d3f13e5323da)
disabled Flerovium:
![image](https://github.com/user-attachments/assets/1546cfe7-f2d0-43eb-80b3-8f958ff6e0c3)

**Comment by MoePus** [comment]
Try 1.1.1. if not fixed you can open a new issue for me, i will find out ^ ^

**Comment by yuusyaasisutanto** [comment]
I tried it, but not fixed...
I'll open new issue, sorry for inconvinience
